version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/etc/google-credentials.json"
      PROJECT_ID: ""
      TRIGGERS_FILTER_REGEX: "^.*$"
    volumes:
      - "/path/to/google-credentials.json:/etc/google-credentials.json"